/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a adaptor.h:adaptor.cpp -p clientproxy.h:clientproxy.cpp dbus/manifest.xml cf.thebone.viper4linux.Gui
 *
 * qdbusxml2cpp is Copyright (C) 2019 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "clientproxy.h"

/*
 * Implementation of interface class CfTheboneViper4linuxGuiInterface
 */

CfTheboneViper4linuxGuiInterface::CfTheboneViper4linuxGuiInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

CfTheboneViper4linuxGuiInterface::~CfTheboneViper4linuxGuiInterface()
{
}

