/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a dbus/serveradaptor.h:dbus/serveradaptor.cpp dbus/manifest.xml cf.thebone.viper4linux.Gui
 *
 * qdbusxml2cpp is Copyright (C) 2019 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbus/serveradaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class GuiAdaptor
 */

GuiAdaptor::GuiAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

GuiAdaptor::~GuiAdaptor()
{
    // destructor
}

void GuiAdaptor::hide()
{
    // handle method call cf.thebone.viper4linux.Gui.hide
    QMetaObject::invokeMethod(parent(), "hide");
}

void GuiAdaptor::raiseWindow()
{
    // handle method call cf.thebone.viper4linux.Gui.raiseWindow
    QMetaObject::invokeMethod(parent(), "raiseWindow");
}

void GuiAdaptor::show()
{
    // handle method call cf.thebone.viper4linux.Gui.show
    QMetaObject::invokeMethod(parent(), "show");
}

